version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: universities_db
    environment:
      MYSQL_DATABASE: universities
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: universities_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/universities
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
